version: "3.7"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webcup_db
      MYSQL_USER: techtitan
      MYSQL_PASSWORD: webcup_dev_2024
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "1024:80"
    environment:
      PMA_USER: techtitan
      PMA_PASSWORD: webcup_dev_2024

volumes:
  db_data: