version: "3.1"
services:
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_USER: webcup24
      POSTGRES_PASSWORD: webcup2442
      POSTGRES_DB: webcup24-db
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: webcup24@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 2k23_admin
    ports:
      - "98:80"